#!/bin/sh
exec tail -n +3 $0

menuentry "Boot from UUID" {
    search --no-floppy --fs-uuid --set=root 0c21ae25-58aa-4153-87f6-ea31b7a8e0f5
    echo    'Loading Linux 6.16.0 ...'
    linux /boot/vmlinuz-6.16.0 root=UUID=0c21ae25-58aa-4153-87f6-ea31b7a8e0f5 rw rootwait rootdelay=50
    echo    'Loading initial ramdisk ...'
    initrd /boot/initrd.img-6.16.0
    echo    'Loading rk3328-roc-cc.dtb'
    devicetree /boot/dtb/rockchip/rk3328-roc-cc.dtb
}
