/*
 * Copyright 2017 Google, Inc
 *
 * SPDX-License-Identifier:     GPL-2.0+
 */

#include "clock.h"
#include "timer.h"

enum {
	/* PLL_CON0 */
	PLL_POSTDIV1_SHIFT		= 12,
	PLL_POSTDIV1_MASK		= 0x7 << PLL_POSTDIV1_SHIFT,
	PLL_FBDIV_SHIFT			= 0,
	PLL_FBDIV_MASK			= 0xfff,

	/* PLL_CON1 */
	PLL_DSMPD_SHIFT			= 12,
	PLL_DSMPD_MASK			= 1 << PLL_DSMPD_SHIFT,
	PLL_INTEGER_MODE		= 1,
	PLL_LOCK_STATUS_SHIFT		= 10,
	PLL_LOCK_STATUS_MASK		= 1 << PLL_LOCK_STATUS_SHIFT,
	PLL_POSTDIV2_SHIFT		= 6,
	PLL_POSTDIV2_MASK		= 0x7 << PLL_POSTDIV2_SHIFT,
	PLL_REFDIV_SHIFT		= 0,
	PLL_REFDIV_MASK			= 0x3f,

	/* PLL_CON2 */
	PLL_FRACDIV_SHIFT		= 0,
	PLL_FRACDIV_MASK		= 0xffffff,

	/* MODE_CON */
	APLL_MODE_SHIFT			= 0,
	NPLL_MODE_SHIFT			= 1,
	DPLL_MODE_SHIFT			= 4,
	CPLL_MODE_SHIFT			= 8,
	GPLL_MODE_SHIFT			= 12,
	PLL_MODE_SLOW			= 0,
	PLL_MODE_NORM,

	/* CLKSEL_CON0 */
	CLK_CORE_PLL_SEL_APLL		= 0,
	CLK_CORE_PLL_SEL_GPLL,
	CLK_CORE_PLL_SEL_DPLL,
	CLK_CORE_PLL_SEL_NPLL,
	CLK_CORE_PLL_SEL_SHIFT		= 6,
	CLK_CORE_PLL_SEL_MASK		= 3 << CLK_CORE_PLL_SEL_SHIFT,
	CLK_CORE_DIV_SHIFT		= 0,
	CLK_CORE_DIV_MASK		= 0x1f,

	/* CLKSEL_CON1 */
	ACLKM_CORE_DIV_SHIFT		= 4,
	ACLKM_CORE_DIV_MASK		= 0x7 << ACLKM_CORE_DIV_SHIFT,
	PCLK_DBG_DIV_SHIFT		= 0,
	PCLK_DBG_DIV_MASK		= 0xF << PCLK_DBG_DIV_SHIFT,

	/* CLKSEL_CON28 */
	ACLK_PERIHP_PLL_SEL_CPLL	= 0,
	ACLK_PERIHP_PLL_SEL_GPLL,
	ACLK_PERIHP_PLL_SEL_HDMIPHY,
	ACLK_PERIHP_PLL_SEL_SHIFT	= 6,
	ACLK_PERIHP_PLL_SEL_MASK	= 3 << ACLK_PERIHP_PLL_SEL_SHIFT,
	ACLK_PERIHP_DIV_CON_SHIFT	= 0,
	ACLK_PERIHP_DIV_CON_MASK	= 0x1f,

	/* CLKSEL_CON29 */
	PCLK_PERIHP_DIV_CON_SHIFT	= 4,
	PCLK_PERIHP_DIV_CON_MASK	= 0x7 << PCLK_PERIHP_DIV_CON_SHIFT,
	HCLK_PERIHP_DIV_CON_SHIFT	= 0,
	HCLK_PERIHP_DIV_CON_MASK	= 3 << HCLK_PERIHP_DIV_CON_SHIFT,

};

void rkclk_set_pll( int clk_id )
{
        if ( clk_id == CLK_CODEC ) {
            *CRU_MODE_CON = ((1 << CPLL_MODE_SHIFT) << 16) | (PLL_MODE_SLOW << CPLL_MODE_SHIFT);
            *CRU_CPLL_CON1 = (PLL_DSMPD_MASK << 16) | (PLL_INTEGER_MODE << PLL_DSMPD_SHIFT);
            *CRU_CPLL_CON0 = ((PLL_FBDIV_MASK | PLL_POSTDIV1_MASK) << 16) | (99 << PLL_FBDIV_SHIFT) | (2 << PLL_POSTDIV1_SHIFT);
            *CRU_CPLL_CON1 = ((PLL_POSTDIV2_MASK | PLL_REFDIV_MASK) << 16) | (1 << PLL_POSTDIV2_SHIFT) | (2 << PLL_REFDIV_SHIFT);
	    while (!(*CRU_CPLL_CON1 & (1 << PLL_LOCK_STATUS_SHIFT))) {
		udelay( 1 );
            }
            *CRU_MODE_CON = ((1 << CPLL_MODE_SHIFT) << 16) | (PLL_MODE_NORM << CPLL_MODE_SHIFT);
        } else if ( clk_id == CLK_GENERAL ) {
            *CRU_MODE_CON = ((1 << GPLL_MODE_SHIFT) << 16) | (PLL_MODE_SLOW << GPLL_MODE_SHIFT);
            *CRU_GPLL_CON1 = (PLL_DSMPD_MASK  << 16) | (PLL_INTEGER_MODE << PLL_DSMPD_SHIFT);
            *CRU_GPLL_CON0 = ((PLL_FBDIV_MASK | PLL_POSTDIV1_MASK) << 16) | (96 << PLL_FBDIV_SHIFT) | (4 << PLL_POSTDIV1_SHIFT);
            *CRU_GPLL_CON1 = ((PLL_POSTDIV2_MASK | PLL_REFDIV_MASK) << 16) | (1 << PLL_POSTDIV2_SHIFT) | (1 << PLL_REFDIV_SHIFT);
            while (!(*CRU_GPLL_CON1 & (1 << PLL_LOCK_STATUS_SHIFT))) {
                udelay( 1 );
            }
            *CRU_MODE_CON = ((1 << GPLL_MODE_SHIFT) << 16) | (PLL_MODE_NORM << GPLL_MODE_SHIFT);
        }
}

void rkclk_init( void )
{
        int aclk_div;
        int hclk_div;
        int pclk_div;

	/* configure gpll cpll */
	rkclk_set_pll( CLK_GENERAL );
	rkclk_set_pll( CLK_CODEC );

        aclk_div = 3;  // GPLL_HZ / PERIHP_ACLK_HZ - 1;
        hclk_div = 1;  // PERIHP_ACLK_HZ / PERIHP_HCLK_HZ - 1;
        pclk_div = 1;  // PERIHP_ACLK_HZ / PERIHP_PCLK_HZ - 1;  was 0

        *CRU_CLKSEL_CON28 = ((ACLK_PERIHP_PLL_SEL_MASK | ACLK_PERIHP_DIV_CON_MASK) << 16) | (ACLK_PERIHP_PLL_SEL_GPLL << ACLK_PERIHP_PLL_SEL_SHIFT | aclk_div << ACLK_PERIHP_DIV_CON_SHIFT);
        *CRU_CLKSEL_CON29 = ((PCLK_PERIHP_DIV_CON_MASK | HCLK_PERIHP_DIV_CON_MASK) << 16) | (pclk_div << PCLK_PERIHP_DIV_CON_SHIFT | hclk_div << HCLK_PERIHP_DIV_CON_SHIFT);
}
